
trigger:
  - master

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'docker build'
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
  - job: Test
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: 'test'
        projects: '**/*.Tests.csproj'